### ISSUE TITLE
UnsupportedOperationException throwing in Language Server for JakartaEE and Language Server for Liberty

### ISSUE THREAD

**Issue by gilbysunil14** [eclipse-lsp4j/lsp4j#853]
lsp4jakarta and lcls output tabs included this exception:

```
Oct 15, 2024 2:44:21 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "$/setTrace",
  "params": {
    "value": "off"
  }
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at io.openliberty.tools.langserver.common.ParentProcessWatcher.lambda$apply$0(ParentProcessWatcher.java:154)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1595)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:586)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 12 more
Caused by: java.lang.UnsupportedOperationException
	at org.eclipse.lsp4j.services.LanguageServer.setTrace(LanguageServer.java:125)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 14 more
```

**Comment by angelozerr** [comment]
You need to implement the method like we did for LemMinx for instance https://github.com/eclipse/lemminx/blob/d3a123531c8b48d6139759beab6ea1fdaeefe158/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/XMLLanguageServer.java#L359

**Comment by jonahgraham** [comment]
> A similar change for setTrace() as was done in eclipse-lsp4j repo for getNotebookDocumentService() here: [04b0c61#diff-c253172d13cae9e4a8c919ba451df40be7096aad30d01638383c6ed0497e7f19R92](https://github.com/eclipse-lsp4j/lsp4j/commit/04b0c6112f0a94140e22b8b15bb5a90d5a0ed851#diff-c253172d13cae9e4a8c919ba451df40be7096aad30d01638383c6ed0497e7f19R92)

Thanks for the report @gilbysunil14 - can you create a PR please?

**Comment by gilbysunil14** [comment]
@jonahgraham, I have created the PR.
